# -*- coding: utf-8 -*-
lines = open('pages/02_P5_Arena.py', 'r', encoding='utf-8').readlines()

new_brief = []
new_brief.append('    st.markdown(f\'<div class="br-ban {v_cls}">{ban_emoji} \ub77c\uc6b4\ub4dc {rn} \u2014 {v_label} \u2705{sc_v} \u274c{wr_v}</div>\', unsafe_allow_html=True)\n')
new_brief.append('    st.markdown("""<style>\n')
new_brief.append('    .note-wrap{background:repeating-linear-gradient(#0d1117,#0d1117 31px,rgba(0,212,255,0.08) 31px,rgba(0,212,255,0.08) 32px);border-radius:14px;border:1.5px solid rgba(0,212,255,0.3);padding:18px 18px 18px 34px;margin:6px 0;position:relative;box-shadow:0 0 20px rgba(0,212,255,0.08);}\n')
new_brief.append('    .note-wrap::before{content:"";position:absolute;left:22px;top:0;bottom:0;width:2px;background:rgba(255,80,80,0.45);border-radius:2px;}\n')
new_brief.append('    .note-qnum{font-size:0.8rem;font-weight:900;letter-spacing:3px;color:#00d4ff;margin-bottom:8px;}\n')
new_brief.append('    .note-sent{font-size:1.55rem;font-weight:700;color:#f0f0f0;line-height:1.75;word-break:keep-all;margin-bottom:10px;}\n')
new_brief.append('    .note-kr{font-size:1.15rem;color:#bbb;line-height:1.65;margin-bottom:8px;}\n')
new_brief.append('    .note-hint{font-size:1.0rem;color:#00d4ff;background:rgba(0,212,255,0.06);border-left:3px solid #00d4ff;padding:7px 12px;border-radius:0 8px 8px 0;line-height:1.5;}\n')
new_brief.append('    @keyframes nextPulse{0%,100%{box-shadow:0 0 20px rgba(255,215,0,0.7);}50%{box-shadow:0 0 50px rgba(255,215,0,1),0 0 90px rgba(255,100,0,0.5);}}\n')
new_brief.append('    .next-rd button{background:linear-gradient(135deg,#1a0d00,#3d2000)!important;border:2px solid #ffd700!important;animation:nextPulse 1.5s ease-in-out infinite!important;color:#ffd700!important;}\n')
new_brief.append('    .next-rd button p{font-size:1.3rem!important;color:#ffd700!important;}\n')
new_brief.append('    .side-btn button{background:transparent!important;border:1px solid #222!important;box-shadow:none!important;animation:none!important;}\n')
new_brief.append('    .side-btn button p{font-size:0.8rem!important;color:#444!important;}\n')
new_brief.append('    .save-btn button{background:transparent!important;border:1px solid #333!important;box-shadow:none!important;animation:none!important;}\n')
new_brief.append('    .save-btn button p{font-size:0.85rem!important;color:#555!important;}\n')
new_brief.append('    </style>""", unsafe_allow_html=True)\n')
new_brief.append('    q = rqs[bi]\n')
new_brief.append('    ok = rrs[bi]\n')
new_brief.append('    sym = "\u2705" if ok else "\u274c"\n')
new_brief.append('    sent = full_sent(q, ok)\n')
new_brief.append('    kr = q.get("kr","")\n')
new_brief.append('    exk = q.get("exk","")\n')
new_brief.append('    st.markdown(f"""\n')
new_brief.append('    <div class="note-wrap">\n')
new_brief.append('        <div class="note-qnum">{sym} Q{bi+1} / {num_qs}</div>\n')
new_brief.append('        <div class="note-sent">{sent}</div>\n')
new_brief.append('        <div class="note-kr">\U0001f4d6 {kr}</div>\n')
new_brief.append('        <div class="note-hint">\U0001f4a1 {exk}</div>\n')
new_brief.append('    </div>\n')
new_brief.append('    """, unsafe_allow_html=True)\n')
new_brief.append('    dot_cols = st.columns(num_qs)\n')
new_brief.append('    for i in range(num_qs):\n')
new_brief.append('        with dot_cols[i]:\n')
new_brief.append('            oi = rrs[i]\n')
new_brief.append('            si = "\u2705" if oi else "\u274c"\n')
new_brief.append('            bt = "primary" if i == bi else "secondary"\n')
new_brief.append('            if st.button(f"{si}{i+1}", key=f"brd_{i}", type=bt, use_container_width=True):\n')
new_brief.append('                st.session_state.br_idx = i; st.rerun()\n')
new_brief.append('    sc1, sc2, sc3 = st.columns([2,3,2])\n')
new_brief.append('    with sc2:\n')
new_brief.append('        st.markdown(\'<div class="save-btn">\', unsafe_allow_html=True)\n')
new_brief.append('        if st.button("\U0001f4be \uc774 \ubb38\uc81c \uc800\uc7a5", key=f"sv_{q[\'id\']}_{bi}", type="secondary", use_container_width=True):\n')
new_brief.append('            item = {"id":q["id"],"text":q["text"],"ch":q["ch"],"a":q["a"],"ex":q.get("ex",""),"exk":q.get("exk",""),"cat":q.get("cat",""),"kr":q.get("kr",""),"tp":q.get("tp","grammar")}\n')
new_brief.append('            save_to_storage([item])\n')
new_brief.append('            st.success("\u2705 \uc800\uc7a5 \uc644\ub8cc!")\n')
new_brief.append('        st.markdown(\'</div>\', unsafe_allow_html=True)\n')
new_brief.append('    st.markdown(\'<div style="height:4px;border-top:1px solid #1a1a1a;margin:6px 0;"></div>\', unsafe_allow_html=True)\n')
new_brief.append('    if was_victory:\n')
new_brief.append('        nrd = st.session_state.round_num + 1\n')
new_brief.append('        st.markdown(\'<div class="next-rd">\', unsafe_allow_html=True)\n')
new_brief.append('        if st.button(f"\u2694\ufe0f \ub77c\uc6b4\ub4dc {nrd}!", type="primary", use_container_width=True, key="btn_next_rd"):\n')
new_brief.append('            st.session_state.round_num += 1\n')
new_brief.append('            for k in ["cq","qi","sc","wrong","ta","ans","sel","round_qs","round_results","br_idx"]:\n')
new_brief.append('                if k in st.session_state: del st.session_state[k]\n')
new_brief.append('            for k,v in D.items():\n')
new_brief.append('                if k not in st.session_state: st.session_state[k]=v\n')
new_brief.append('            qs = pick5(st.session_state.mode)\n')
new_brief.append('            st.session_state.round_qs = qs; st.session_state.cq = qs[0]\n')
new_brief.append('            st.session_state.qst = time.time(); st.session_state.phase = "battle"; st.rerun()\n')
new_brief.append('        st.markdown(\'</div>\', unsafe_allow_html=True)\n')
new_brief.append('        nc1, nc2 = st.columns(2)\n')
new_brief.append('        with nc1:\n')
new_brief.append('            st.markdown(\'<div class="side-btn">\', unsafe_allow_html=True)\n')
new_brief.append('            if st.button("\U0001f3e0 \ub85c\ube44", type="secondary", use_container_width=True, key="btn_lobby_v"):\n')
new_brief.append('                for k in ["cq","qi","sc","wrong","ta","ans","sel","round_qs","round_results","br_idx"]:\n')
new_brief.append('                    if k in st.session_state: del st.session_state[k]\n')
new_brief.append('                for k,v in D.items():\n')
new_brief.append('                    if k not in st.session_state: st.session_state[k]=v\n')
new_brief.append('                st.session_state.phase = "lobby"; st.rerun()\n')
new_brief.append('            st.markdown(\'</div>\', unsafe_allow_html=True)\n')
new_brief.append('        with nc2:\n')
new_brief.append('            st.markdown(\'<div class="side-btn">\', unsafe_allow_html=True)\n')
new_brief.append('            if st.button("\U0001f30d \uba54\uc778\ud5c8\ube0c", type="secondary", use_container_width=True, key="btn_main_v"):\n')
new_brief.append('                st.session_state._p5_just_left = True\n')
new_brief.append('                st.session_state.ans = False\n')
new_brief.append('                st.session_state["_battle_entry_ans_reset"] = True\n')
new_brief.append('                st.switch_page("main_hub.py")\n')
new_brief.append('            st.markdown(\'</div>\', unsafe_allow_html=True)\n')
new_brief.append('    else:\n')
new_brief.append('        nc1, nc2, nc3 = st.columns(3)\n')
new_brief.append('        with nc1:\n')
new_brief.append('            st.markdown(\'<div class="next-rd">\', unsafe_allow_html=True)\n')
new_brief.append('            if st.button("\U0001f504 \uc7ac\ub3c4\uc804", type="primary", use_container_width=True, key="btn_retry"):\n')
new_brief.append('                for k in ["cq","qi","sc","wrong","ta","ans","sel","round_qs","round_results","br_idx"]:\n')
new_brief.append('                    if k in st.session_state: del st.session_state[k]\n')
new_brief.append('                for k,v in D.items():\n')
new_brief.append('                    if k not in st.session_state: st.session_state[k]=v\n')
new_brief.append('                qs = pick5(st.session_state.mode)\n')
new_brief.append('                st.session_state.round_qs = qs; st.session_state.cq = qs[0]\n')
new_brief.append('                st.session_state.qst = time.time(); st.session_state.phase = "battle"; st.rerun()\n')
new_brief.append('            st.markdown(\'</div>\', unsafe_allow_html=True)\n')
new_brief.append('        with nc2:\n')
new_brief.append('            st.markdown(\'<div class="side-btn">\', unsafe_allow_html=True)\n')
new_brief.append('            if st.button("\U0001f3e0 \ub85c\ube44", type="secondary", use_container_width=True, key="btn_lobby_l"):\n')
new_brief.append('                for k in ["cq","qi","sc","wrong","ta","ans","sel","round_qs","round_results","br_idx"]:\n')
new_brief.append('                    if k in st.session_state: del st.session_state[k]\n')
new_brief.append('                for k,v in D.items():\n')
new_brief.append('                    if k not in st.session_state: st.session_state[k]=v\n')
new_brief.append('                st.session_state.phase = "lobby"; st.rerun()\n')
new_brief.append('            st.markdown(\'</div>\', unsafe_allow_html=True)\n')
new_brief.append('        with nc3:\n')
new_brief.append('            st.markdown(\'<div class="side-btn">\', unsafe_allow_html=True)\n')
new_brief.append('            if st.button("\U0001f30d \uba54\uc778\ud5c8\ube0c", type="secondary", use_container_width=True, key="btn_main_l"):\n')
new_brief.append('                st.session_state._p5_just_left = True\n')
new_brief.append('                st.session_state.ans = False\n')
new_brief.append('                st.session_state["_battle_entry_ans_reset"] = True\n')
new_brief.append('                st.switch_page("main_hub.py")\n')
new_brief.append('            st.markdown(\'</div>\', unsafe_allow_html=True)\n')

# 542줄(인덱스 541)부터 629줄(인덱스 629)까지 교체
new_lines = lines[:541] + new_brief + lines[629:]
open('pages/02_P5_Arena.py', 'w', encoding='utf-8').writelines(new_lines)
c = open('pages/02_P5_Arena.py', 'r', encoding='utf-8').read()
print('note-wrap:', 'note-wrap' in c)
print('done!')
