# -*- coding: utf-8 -*-
content = open('pages/02_P5_Arena.py', 'r', encoding='utf-8').read()

# victory 하단 버튼 3개 가로 HTML로 교체
old_v = '    _btn_style = "flex:1;display:block;text-align:center;padding:6px 2px;font-size:0.68rem;font-weight:300;border:1px solid rgba(255,255,255,0.18);border-radius:8px;text-decoration:none;background:transparent;color:#555;letter-spacing:0.5px;"\n    if was_victory:\n        nrd = st.session_state.round_num + 1\n        st.markdown(f\'<div style="display:flex;gap:6px;margin:4px 0;"><a href="?act=next" target="_self" style="{_btn_style}">\u2694\ufe0f \ub77c\uc6b4\ub4dc {nrd}!</a><a href="?act=lobby" target="_self" style="{_btn_style}">\U0001f3e0 \ub85c\ube44</a></div>\', unsafe_allow_html=True)\n        if st.button("\U0001f30d \uba54\uc778\ud5c8\ube0c", type="secondary", use_container_width=True, key="btn_main_v"):\n            st.session_state._p5_just_left = True\n            st.session_state.ans = False\n            st.session_state["_battle_entry_ans_reset"] = True\n            st.switch_page("main_hub.py")\n    else:\n        st.markdown(f\'<div style="display:flex;gap:6px;margin:4px 0;"><a href="?act=retry" target="_self" style="{_btn_style}">\U0001f504 \uc7ac\ub3c4\uc804</a><a href="?act=lobby" target="_self" style="{_btn_style}">\U0001f3e0 \ub85c\ube44</a></div>\', unsafe_allow_html=True)\n        if st.button("\U0001f30d \uba54\uc778\ud5c8\ube0c", type="secondary", use_container_width=True, key="btn_main_l"):\n            st.session_state._p5_just_left = True\n            st.session_state.ans = False\n            st.session_state["_battle_entry_ans_reset"] = True\n            st.switch_page("main_hub.py")\n'

new_v = '    _bs = "flex:1;display:block;text-align:center;padding:8px 2px;font-size:0.68rem;font-weight:300;border:1px solid #1a1a1a;border-radius:8px;text-decoration:none;background:transparent;color:#555;letter-spacing:0.5px;"\n    _nav_main = st.query_params.get("act_main","")\n    if _nav_main == "go":\n        st.query_params.clear()\n        st.session_state._p5_just_left = True\n        st.session_state.ans = False\n        st.session_state["_battle_entry_ans_reset"] = True\n        st.switch_page("main_hub.py")\n    if was_victory:\n        nrd = st.session_state.round_num + 1\n        st.markdown(f\'<div style="display:flex;gap:6px;margin:4px 0;"><a href="?act=next" target="_self" style="{_bs}">\u2694\ufe0f \ub77c\uc6b4\ub4dc {nrd}!</a><a href="?act=lobby" target="_self" style="{_bs}">\U0001f3e0 \ub85c\ube44</a><a href="?act_main=go" target="_self" style="{_bs}">\U0001f30d \uba54\uc778\ud5c8\ube0c</a></div>\', unsafe_allow_html=True)\n    else:\n        st.markdown(f\'<div style="display:flex;gap:6px;margin:4px 0;"><a href="?act=retry" target="_self" style="{_bs}">\U0001f504 \uc7ac\ub3c4\uc804</a><a href="?act=lobby" target="_self" style="{_bs}">\U0001f3e0 \ub85c\ube44</a><a href="?act_main=go" target="_self" style="{_bs}">\U0001f30d \uba54\uc778\ud5c8\ube0c</a></div>\', unsafe_allow_html=True)\n'

r = content.replace(old_v, new_v, 1)
print('replaced:', r != content)
content = r

open('pages/02_P5_Arena.py', 'w', encoding='utf-8').write(content)
c = open('pages/02_P5_Arena.py', 'r', encoding='utf-8').read()
print('3btn ok:', 'act_main=go' in c)
print('done!')
