import sys, ast
sys.stdout.reconfigure(encoding="utf-8")

with open(r"C:\Users\최정은\Desktop\snapq_toeic_V3\pages\03_오답전장.py", "r", encoding="utf-8-sig") as f:
    content = f.read()

start_marker = 'elif st.session_state.sg_phase == "survival":'
end_marker = 'elif st.session_state.sg_phase == "survival_result":'
start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

new_survival = (
'elif st.session_state.sg_phase == "survival":\n'
'    if not voca_data:\n'
'        st.warning("저장된 문장이 없습니다! P7전장 브리핑에서 문장을 저장하세요.")\n'
'        if st.button("돌아가기"): st.session_state.sg_phase="lobby"; st.session_state.rv_battle=None; st.session_state.rv_mode=None; st.rerun()\n'
'        st.stop()\n'
'    if "sb_idx" not in st.session_state: st.session_state.sb_idx=0\n'
'    if "sb_pool" not in st.session_state:\n'
'        pool=[v for v in voca_data if v.get("sentences")]\n'
'        nosent=[v for v in voca_data if not v.get("sentences")]\n'
'        random.shuffle(pool); random.shuffle(nosent)\n'
'        st.session_state.sb_pool=pool+nosent\n'
'    if "sb_clicked_word" not in st.session_state: st.session_state.sb_clicked_word=None\n'
'    if "sb_last_idx" not in st.session_state: st.session_state.sb_last_idx=-1\n'
'    pool=st.session_state.sb_pool\n'
'    idx=st.session_state.sb_idx\n'
'    total=len(pool)\n'
'    if idx>=total:\n'
'        st.markdown(\'\'\'<div style="text-align:center;padding:2rem;background:#f8fff8;border-radius:16px;border:1px solid #c0dd97;">\n'
'            <div style="font-size:2rem;">🎉</div>\n'
'            <div style="font-size:1.4rem;font-weight:700;color:#27500a;margin-top:8px;">모든 문장 완료!</div>\n'
'            <div style="font-size:1rem;color:#639922;margin-top:4px;">이제 시험모드에서 증명하라!</div>\n'
'        </div>\'\'\', unsafe_allow_html=True)\n'
'        c1,c2=st.columns(2)\n'
'        with c1:\n'
'            if st.button("⚡ 시험모드 도전!",key="sb_go_exam",type="primary",use_container_width=True):\n'
'                st.session_state.sg_combo_score=0; st.session_state.sg_combo_count=0\n'
'                st.session_state.sg_combo_idx=0; st.session_state.sg_combo_start=time.time()\n'
'                st.session_state.sg_combo_over=False; st.session_state.sg_combo_results=[]\n'
'                if "sg_combo_pool" in st.session_state: del st.session_state.sg_combo_pool\n'
'                st.session_state.rv_mode="p7e"; st.session_state.sg_phase="combo_rush"; st.rerun()\n'
'        with c2:\n'
'            if st.button("🔄 처음부터",key="sb_restart",type="secondary",use_container_width=True):\n'
'                for k in ["sb_idx","sb_pool","sb_clicked_word","sb_last_idx"]:\n'
'                    if k in st.session_state: del st.session_state[k]\n'
'                st.rerun()\n'
'        st.stop()\n'
'    if st.session_state.sb_last_idx != idx:\n'
'        st.session_state.sb_clicked_word = None\n'
'        st.session_state.sb_last_idx = idx\n'
'    item=pool[idx]; expr=item.get("expr",""); sentences=item.get("sentences",[])\n'
'    sentence=sentences[0] if sentences else f"The company will {expr} as required."\n'
'    kr_full=item.get("kr","") or item.get("meaning","")\n'
'    kr_sents=[x.strip() for x in kr_full.replace("!","!|").replace("?","?|").replace(".",".|").split("|") if x.strip()]\n'
'    sent_kr=kr_sents[0] if kr_sents else kr_full\n'
'    clicked=st.session_state.sb_clicked_word\n'
'    st.markdown(f\'\'\'<div style="background:#1a1a2e;border:1.5px solid #4488ff;border-radius:16px;padding:10px 14px;text-align:center;margin-bottom:10px;">\n'
'        <div style="font-size:1.0rem;font-weight:700;color:#4488ff;">📖 문장 학습 배틀</div>\n'
'        <div style="font-size:0.85rem;color:#aaa;margin-top:2px;">{idx+1} / {total} 문장</div>\n'
'        <div style="background:#0a0a1a;border-radius:6px;height:6px;margin-top:6px;"><div style="background:linear-gradient(90deg,#4488ff,#44ccff);height:6px;border-radius:6px;width:{int((idx/max(total,1))*100)}%;"></div></div>\n'
'    </div>\'\'\', unsafe_allow_html=True)\n'
'    import re as _re4\n'
'    words_en=sentence.split()\n'
'    en_clean=[w.strip(".,!?;:()") for w in words_en]\n'
'    clicked_pos=None\n'
'    if clicked:\n'
'        for i,w in enumerate(en_clean):\n'
'            if w.lower()==clicked: clicked_pos=i; break\n'
'    en_html=\'<div style="background:#1a1a2e;border:1px solid #333;border-radius:12px;padding:12px 14px;margin-bottom:4px;"><div style="font-size:0.7rem;color:#666;margin-bottom:8px;letter-spacing:2px;">ENGLISH — 단어를 탭하세요</div><div style="line-height:2.4;">"\'\n'
'    for wi,word in enumerate(words_en):\n'
'        clean=en_clean[wi]\n'
'        is_active=clicked==clean.lower()\n'
'        if is_active:\n'
'            style="background:#1a3a6b;border:1.5px solid #4488ff;color:#88ccff;font-weight:700;padding:4px 8px;border-radius:6px;cursor:pointer;font-size:1.1rem;display:inline-block;margin:2px;"\n'
'        else:\n'
'            style="color:#ffffff;font-weight:600;padding:4px 8px;border-radius:6px;cursor:pointer;font-size:1.1rem;display:inline-block;margin:2px;border:1px solid transparent;"\n'
'        en_html+=f\'<span style="{style}" onclick="window.parent.postMessage({{type:\'\'clicked_word\'\',word:\'\'{clean.lower()}\'\'}},\'\'*\'\')">{word}</span> \'\n'
'    en_html+=\'</div></div>\'\n'
'    st.markdown(en_html, unsafe_allow_html=True)\n'
'    st.markdown(\'<div style="text-align:center;color:#555;font-size:1.0rem;margin:4px 0;">↕</div>\', unsafe_allow_html=True)\n'
'    words_kr=sent_kr.replace(",","").split()\n'
'    kr_html=\'<div style="background:#fffff5;border:1px solid #e8e0c8;border-radius:12px;padding:12px 14px;"><div style="font-size:0.7rem;color:#888;margin-bottom:8px;letter-spacing:2px;">KOREAN</div><div style="line-height:2.4;">"\'\n'
'    for ki,kw in enumerate(words_kr):\n'
'        if clicked_pos is not None:\n'
'            ratio=clicked_pos/max(len(en_clean)-1,1)\n'
'            kr_center=int(ratio*(len(words_kr)-1))\n'
'            if abs(ki-kr_center)<=1:\n'
'                kr_html+=f\'<span style="background:#faeeda;color:#633806;font-weight:700;padding:4px 8px;border-radius:6px;margin:2px;display:inline-block;font-size:1.05rem;">{kw}</span> \'\n'
'            else:\n'
'                kr_html+=f\'<span style="color:#333;padding:4px 4px;margin:2px;display:inline-block;font-size:1.05rem;">{kw}</span> \'\n'
'        else:\n'
'            kr_html+=f\'<span style="color:#333;padding:4px 4px;margin:2px;display:inline-block;font-size:1.05rem;">{kw}</span> \'\n'
'    kr_html+=\'</div></div>\'\n'
'    st.markdown(kr_html, unsafe_allow_html=True)\n'
'    st.markdown(\'<div style="text-align:center;font-size:0.8rem;color:#888;margin:6px 0;">👆 영어 단어 탭 → 한글 형광 표시!</div>\', unsafe_allow_html=True)\n'
'    # 단어 클릭 처리 - 버튼 방식\n'
'    if words_en:\n'
'        num_cols=min(len(words_en),6)\n'
'        btn_cols=st.columns(num_cols)\n'
'        for wi,word in enumerate(words_en):\n'
'            clean=en_clean[wi]\n'
'            with btn_cols[wi%num_cols]:\n'
'                is_active=clicked==clean.lower()\n'
'                if st.button(word,key=f"enw_{idx}_{wi}",type="primary" if is_active else "secondary",use_container_width=True):\n'
'                    st.session_state.sb_clicked_word=clean.lower(); st.rerun()\n'
'    c1,c2,c3=st.columns(3)\n'
'    with c1:\n'
'        if st.button("⏭ 건너뛰기",key=f"sb_skip_{idx}",use_container_width=True):\n'
'            st.session_state.sb_idx=idx+1; st.session_state.sb_clicked_word=None; st.rerun()\n'
'    with c2:\n'
'        if st.button("✅ 다음 문장!",key="sb_next",type="primary",use_container_width=True):\n'
'            st.session_state.sb_idx=idx+1; st.session_state.sb_clicked_word=None; st.rerun()\n'
'    with c3:\n'
'        if st.button("⚡ 시험 바로가기",key="sb_exam_now",use_container_width=True):\n'
'            st.session_state.sg_combo_score=0; st.session_state.sg_combo_count=0\n'
'            st.session_state.sg_combo_idx=0; st.session_state.sg_combo_start=time.time()\n'
'            st.session_state.sg_combo_over=False; st.session_state.sg_combo_results=[]\n'
'            if "sg_combo_pool" in st.session_state: del st.session_state.sg_combo_pool\n'
'            st.session_state.rv_mode="p7e"; st.session_state.sg_phase="combo_rush"; st.rerun()\n'
'\n'
)

content = content[:start_idx] + new_survival + content[end_idx:]
with open(r"C:\Users\최정은\Desktop\snapq_toeic_V3\pages\03_오답전장.py", "w", encoding="utf-8") as f:
    f.write(content)
try:
    ast.parse(content)
    print("성공! 문법 OK!")
except SyntaxError as e:
    print(f"에러: {e}")
