import json, os, sys

# P7 PASSAGES 데이터 (전체 표현+문장+해석 매핑)
EXPR_MAP = {
    "be fully operational": {"sentences": ["GreenTech Solutions has announced plans to open a new research facility in Austin, Texas.", "The company expects the facility to be fully operational by the third quarter of next year."], "kr": "GreenTech Solutions는 텍사스 오스틴에 새 연구 시설을 열 계획을 발표했다. 회사는 내년 3분기까지 시설이 완전히 가동될 것으로 예상한다."},
    "announce plans to": {"sentences": ["GreenTech Solutions has announced plans to open a new research facility in Austin, Texas.", "The company expects the facility to be fully operational by the third quarter of next year."], "kr": "GreenTech Solutions는 텍사스 오스틴에 새 연구 시설을 열 계획을 발표했다. 회사는 내년 3분기까지 시설이 완전히 가동될 것으로 예상한다."},
    "the third quarter": {"sentences": ["GreenTech Solutions has announced plans to open a new research facility in Austin, Texas.", "The company expects the facility to be fully operational by the third quarter of next year."], "kr": "GreenTech Solutions는 텍사스 오스틴에 새 연구 시설을 열 계획을 발표했다. 회사는 내년 3분기까지 시설이 완전히 가동될 것으로 예상한다."},
    "focus on": {"sentences": ["According to CEO Maria Chen, the facility will focus on developing sustainable energy storage systems.", "The project is expected to create over 200 jobs in the local community.", "GreenTech has already secured $50 million in funding from private investors."], "kr": "CEO Maria Chen에 따르면 시설은 지속 가능한 에너지 저장 시스템 개발에 집중할 것이다. 이 프로젝트는 지역 사회에 200개 이상의 일자리를 창출할 것으로 예상된다. GreenTech는 이미 민간 투자자로부터 5천만 달러의 자금을 확보했다."},
    "secure funding": {"sentences": ["According to CEO Maria Chen, the facility will focus on developing sustainable energy storage systems.", "The project is expected to create over 200 jobs in the local community.", "GreenTech has already secured $50 million in funding from private investors."], "kr": "CEO Maria Chen에 따르면 시설은 지속 가능한 에너지 저장 시스템 개발에 집중할 것이다. 이 프로젝트는 지역 사회에 200개 이상의 일자리를 창출할 것으로 예상된다. GreenTech는 이미 민간 투자자로부터 5천만 달러의 자금을 확보했다."},
    "sustainable": {"sentences": ["According to CEO Maria Chen, the facility will focus on developing sustainable energy storage systems.", "The project is expected to create over 200 jobs in the local community.", "GreenTech has already secured $50 million in funding from private investors."], "kr": "CEO Maria Chen에 따르면 시설은 지속 가능한 에너지 저장 시스템 개발에 집중할 것이다. 이 프로젝트는 지역 사회에 200개 이상의 일자리를 창출할 것으로 예상된다. GreenTech는 이미 민간 투자자로부터 5천만 달러의 자금을 확보했다."},
    "tax incentives": {"sentences": ["Local officials have expressed strong support for the project, citing its potential economic benefits.", "The city of Austin has offered tax incentives to encourage GreenTech's investment in the region.", "Construction of the facility is scheduled to begin in early January and will take approximately 14 months."], "kr": "지역 관리들은 잠재적 경제적 이점을 들어 프로젝트를 강력히 지지했다. 오스틴 시는 이 지역에 대한 GreenTech의 투자를 장려하기 위해 세금 혜택을 제공했다. 시설 건설은 1월 초에 시작되어 약 14개월이 소요될 예정이다."},
    "approximately": {"sentences": ["Local officials have expressed strong support for the project, citing its potential economic benefits.", "The city of Austin has offered tax incentives to encourage GreenTech's investment in the region.", "Construction of the facility is scheduled to begin in early January and will take approximately 14 months."], "kr": "지역 관리들은 잠재적 경제적 이점을 들어 프로젝트를 강력히 지지했다. 오스틴 시는 이 지역에 대한 GreenTech의 투자를 장려하기 위해 세금 혜택을 제공했다. 시설 건설은 1월 초에 시작되어 약 14개월이 소요될 예정이다."},
    "be scheduled to": {"sentences": ["Local officials have expressed strong support for the project, citing its potential economic benefits.", "The city of Austin has offered tax incentives to encourage GreenTech's investment in the region.", "Construction of the facility is scheduled to begin in early January and will take approximately 14 months."], "kr": "지역 관리들은 잠재적 경제적 이점을 들어 프로젝트를 강력히 지지했다. 오스틴 시는 이 지역에 대한 GreenTech의 투자를 장려하기 위해 세금 혜택을 제공했다. 시설 건설은 1월 초에 시작되어 약 14개월이 소요될 예정이다."},
    "be approved for": {"sentences": ["Dear Mr. Thompson, I am writing to inform you that your annual membership at Riverside Fitness Club has been approved for renewal.", "Your new membership period will begin on March 1 and will remain valid for twelve months."], "kr": "Thompson씨에게 Riverside Fitness Club의 연간 회원권 갱신이 승인되었음을 알립니다. 새 회원 기간은 3월 1일에 시작되며 12개월간 유효합니다."},
    "renewal": {"sentences": ["Dear Mr. Thompson, I am writing to inform you that your annual membership at Riverside Fitness Club has been approved for renewal.", "Your new membership period will begin on March 1 and will remain valid for twelve months."], "kr": "Thompson씨에게 Riverside Fitness Club의 연간 회원권 갱신이 승인되었음을 알립니다. 새 회원 기간은 3월 1일에 시작되며 12개월간 유효합니다."},
    "remain valid": {"sentences": ["Dear Mr. Thompson, I am writing to inform you that your annual membership at Riverside Fitness Club has been approved for renewal.", "Your new membership period will begin on March 1 and will remain valid for twelve months."], "kr": "Thompson씨에게 Riverside Fitness Club의 연간 회원권 갱신이 승인되었음을 알립니다. 새 회원 기간은 3월 1일에 시작되며 12개월간 유효합니다."},
    "be entitled to": {"sentences": ["As a valued member, you are entitled to a 15 percent discount on all personal training sessions.", "Additionally, we have recently upgraded our swimming pool and added a new yoga studio on the second floor.", "These improvements were made based on feedback from members like you."], "kr": "소중한 회원으로서 모든 개인 트레이닝 세션에 15% 할인을 받을 수 있습니다. 또한 수영장을 업그레이드하고 2층에 새 요가 스튜디오를 추가했습니다. 이 개선 사항은 회원들의 피드백을 기반으로 이루어졌습니다."},
    "based on feedback": {"sentences": ["As a valued member, you are entitled to a 15 percent discount on all personal training sessions.", "Additionally, we have recently upgraded our swimming pool and added a new yoga studio on the second floor.", "These improvements were made based on feedback from members like you."], "kr": "소중한 회원으로서 모든 개인 트레이닝 세션에 15% 할인을 받을 수 있습니다. 또한 수영장을 업그레이드하고 2층에 새 요가 스튜디오를 추가했습니다. 이 개선 사항은 회원들의 피드백을 기반으로 이루어졌습니다."},
    "complimentary": {"sentences": ["As a valued member, you are entitled to a 15 percent discount on all personal training sessions.", "Additionally, we have recently upgraded our swimming pool and added a new yoga studio on the second floor.", "These improvements were made based on feedback from members like you."], "kr": "소중한 회원으로서 모든 개인 트레이닝 세션에 15% 할인을 받을 수 있습니다. 또한 수영장을 업그레이드하고 2층에 새 요가 스튜디오를 추가했습니다. 이 개선 사항은 회원들의 피드백을 기반으로 이루어졌습니다."},
    "due by": {"sentences": ["Please note that the annual membership fee of $480 is due by February 20.", "Payment can be made online through our website or in person at the front desk.", "If you have any questions regarding your membership, please do not hesitate to contact us at (555) 234-5678."], "kr": "연간 회원비 $480는 2월 20일까지 납부해야 합니다. 결제는 웹사이트 또는 프론트 데스크에서 직접 할 수 있습니다. 회원권 관련 문의는 (555) 234-5678로 연락하세요."},
    "do not hesitate to": {"sentences": ["Please note that the annual membership fee of $480 is due by February 20.", "Payment can be made online through our website or in person at the front desk.", "If you have any questions regarding your membership, please do not hesitate to contact us at (555) 234-5678."], "kr": "연간 회원비 $480는 2월 20일까지 납부해야 합니다. 결제는 웹사이트 또는 프론트 데스크에서 직접 할 수 있습니다. 회원권 관련 문의는 (555) 234-5678로 연락하세요."},
    "regarding": {"sentences": ["Please note that the annual membership fee of $480 is due by February 20.", "Payment can be made online through our website or in person at the front desk.", "If you have any questions regarding your membership, please do not hesitate to contact us at (555) 234-5678."], "kr": "연간 회원비 $480는 2월 20일까지 납부해야 합니다. 결제는 웹사이트 또는 프론트 데스크에서 직접 할 수 있습니다. 회원권 관련 문의는 (555) 234-5678로 연락하세요."},
    "be closed for maintenance": {"sentences": ["All employees are hereby notified that the main parking garage will be closed for maintenance starting Monday, April 7.", "The closure is expected to last for two weeks."], "kr": "모든 직원에게 주 주차장이 4월 7일 월요일부터 유지보수를 위해 폐쇄됨을 알립니다. 폐쇄는 2주간 지속될 예정입니다."},
    "hereby": {"sentences": ["All employees are hereby notified that the main parking garage will be closed for maintenance starting Monday, April 7.", "The closure is expected to last for two weeks."], "kr": "모든 직원에게 주 주차장이 4월 7일 월요일부터 유지보수를 위해 폐쇄됨을 알립니다. 폐쇄는 2주간 지속될 예정입니다."},
    "closure": {"sentences": ["All employees are hereby notified that the main parking garage will be closed for maintenance starting Monday, April 7.", "The closure is expected to last for two weeks."], "kr": "모든 직원에게 주 주차장이 4월 7일 월요일부터 유지보수를 위해 폐쇄됨을 알립니다. 폐쇄는 2주간 지속될 예정입니다."},
    "temporary": {"sentences": ["During this period, employees may use the temporary parking lot located at 45 Oak Street, approximately a five-minute walk from the office.", "A free shuttle service will operate between the temporary lot and the main entrance every 15 minutes from 7:00 A.M. to 7:00 P.M.", "Employees who wish to use the shuttle should display their company ID badges."], "kr": "이 기간 동안 직원들은 사무실에서 도보 약 5분 거리인 45 Oak Street의 임시 주차장을 이용할 수 있습니다. 무료 셔틀이 오전 7시부터 오후 7시까지 15분 간격으로 운행됩니다. 셔틀 이용 시 사원증을 제시해야 합니다."},
    "display": {"sentences": ["During this period, employees may use the temporary parking lot located at 45 Oak Street, approximately a five-minute walk from the office.", "A free shuttle service will operate between the temporary lot and the main entrance every 15 minutes from 7:00 A.M. to 7:00 P.M.", "Employees who wish to use the shuttle should display their company ID badges."], "kr": "이 기간 동안 직원들은 사무실에서 도보 약 5분 거리인 45 Oak Street의 임시 주차장을 이용할 수 있습니다. 무료 셔틀이 오전 7시부터 오후 7시까지 15분 간격으로 운행됩니다. 셔틀 이용 시 사원증을 제시해야 합니다."},
    "apologize for any inconvenience": {"sentences": ["We apologize for any inconvenience this may cause and appreciate your patience during the renovation.", "The upgraded garage will feature additional spaces, improved lighting, and electric vehicle charging stations.", "For further information, please contact the Facilities Department at extension 4200."], "kr": "불편을 끼쳐 죄송하며 리모델링 기간 동안 양해 부탁드립니다. 업그레이드된 주차장에는 추가 공간, 개선된 조명, 전기차 충전소가 설치됩니다. 추가 정보는 시설 관리부 내선 4200으로 연락하세요."},
    "for further information": {"sentences": ["We apologize for any inconvenience this may cause and appreciate your patience during the renovation.", "The upgraded garage will feature additional spaces, improved lighting, and electric vehicle charging stations.", "For further information, please contact the Facilities Department at extension 4200."], "kr": "불편을 끼쳐 죄송하며 리모델링 기간 동안 양해 부탁드립니다. 업그레이드된 주차장에는 추가 공간, 개선된 조명, 전기차 충전소가 설치됩니다. 추가 정보는 시설 관리부 내선 4200으로 연락하세요."},
    "feature": {"sentences": ["We apologize for any inconvenience this may cause and appreciate your patience during the renovation.", "The upgraded garage will feature additional spaces, improved lighting, and electric vehicle charging stations.", "For further information, please contact the Facilities Department at extension 4200."], "kr": "불편을 끼쳐 죄송하며 리모델링 기간 동안 양해 부탁드립니다. 업그레이드된 주차장에는 추가 공간, 개선된 조명, 전기차 충전소가 설치됩니다. 추가 정보는 시설 관리부 내선 4200으로 연락하세요."},
    "at no additional charge": {"sentences": ["The Westfield Convention Center offers a variety of meeting rooms and event spaces for corporate and private use.", "All rooms are equipped with high-speed Wi-Fi, projectors, and sound systems at no additional charge."], "kr": "Westfield Convention Center는 기업 및 개인용 다양한 회의실과 이벤트 공간을 제공합니다. 모든 회의실에는 고속 Wi-Fi, 프로젝터, 음향 시스템이 추가 비용 없이 갖추어져 있습니다."},
    "be equipped with": {"sentences": ["The Westfield Convention Center offers a variety of meeting rooms and event spaces for corporate and private use.", "All rooms are equipped with high-speed Wi-Fi, projectors, and sound systems at no additional charge."], "kr": "Westfield Convention Center는 기업 및 개인용 다양한 회의실과 이벤트 공간을 제공합니다. 모든 회의실에는 고속 Wi-Fi, 프로젝터, 음향 시스템이 추가 비용 없이 갖추어져 있습니다."},
    "corporate": {"sentences": ["The Westfield Convention Center offers a variety of meeting rooms and event spaces for corporate and private use.", "All rooms are equipped with high-speed Wi-Fi, projectors, and sound systems at no additional charge."], "kr": "Westfield Convention Center는 기업 및 개인용 다양한 회의실과 이벤트 공간을 제공합니다. 모든 회의실에는 고속 Wi-Fi, 프로젝터, 음향 시스템이 추가 비용 없이 갖추어져 있습니다."},
    "upon request": {"sentences": ["Catering services are available upon request and must be arranged at least 48 hours in advance.", "A dedicated event coordinator will be assigned to assist with planning and setup for groups of 50 or more.", "Discounted rates are offered for bookings made more than 30 days prior to the event date."], "kr": "케이터링 서비스는 요청 시 이용 가능하며 최소 48시간 전에 준비해야 합니다. 50명 이상 그룹에는 전담 이벤트 코디네이터가 배정됩니다. 행사일 30일 이전 예약 시 할인 요금이 적용됩니다."},
    "in advance": {"sentences": ["Catering services are available upon request and must be arranged at least 48 hours in advance.", "A dedicated event coordinator will be assigned to assist with planning and setup for groups of 50 or more.", "Discounted rates are offered for bookings made more than 30 days prior to the event date."], "kr": "케이터링 서비스는 요청 시 이용 가능하며 최소 48시간 전에 준비해야 합니다. 50명 이상 그룹에는 전담 이벤트 코디네이터가 배정됩니다. 행사일 30일 이전 예약 시 할인 요금이 적용됩니다."},
    "prior to": {"sentences": ["Catering services are available upon request and must be arranged at least 48 hours in advance.", "A dedicated event coordinator will be assigned to assist with planning and setup for groups of 50 or more.", "Discounted rates are offered for bookings made more than 30 days prior to the event date."], "kr": "케이터링 서비스는 요청 시 이용 가능하며 최소 48시간 전에 준비해야 합니다. 50명 이상 그룹에는 전담 이벤트 코디네이터가 배정됩니다. 행사일 30일 이전 예약 시 할인 요금이 적용됩니다."},
    "conveniently located": {"sentences": ["The center is conveniently located near the downtown business district, with easy access to public transportation.", "On-site parking is available for up to 500 vehicles, and valet parking can be arranged for an additional fee."], "kr": "센터는 도심 비즈니스 지구 근처에 편리하게 위치해 있으며 대중교통 이용이 쉽습니다. 최대 500대 수용 가능한 주차장이 있으며 추가 요금으로 발렛 파킹도 가능합니다."},
    "on-site": {"sentences": ["The center is conveniently located near the downtown business district, with easy access to public transportation.", "On-site parking is available for up to 500 vehicles, and valet parking can be arranged for an additional fee."], "kr": "센터는 도심 비즈니스 지구 근처에 편리하게 위치해 있으며 대중교통 이용이 쉽습니다. 최대 500대 수용 가능한 주차장이 있으며 추가 요금으로 발렛 파킹도 가능합니다."},
    "valet parking": {"sentences": ["The center is conveniently located near the downtown business district, with easy access to public transportation.", "On-site parking is available for up to 500 vehicles, and valet parking can be arranged for an additional fee."], "kr": "센터는 도심 비즈니스 지구 근처에 편리하게 위치해 있으며 대중교통 이용이 쉽습니다. 최대 500대 수용 가능한 주차장이 있으며 추가 요금으로 발렛 파킹도 가능합니다."},
}

# storage_data.json 경로
path = sys.argv[1] if len(sys.argv) > 1 else "storage_data.json"

if not os.path.exists(path):
    print(f"ERROR: {path} not found"); sys.exit(1)

with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

if isinstance(data, list):
    data = {"saved_questions": data, "saved_expressions": []}

exprs = data.get("saved_expressions", [])
updated = 0
for e in exprs:
    expr_key = e.get("expr", "")
    if expr_key in EXPR_MAP and "sentences" not in e:
        e["sentences"] = EXPR_MAP[expr_key]["sentences"]
        e["kr"] = EXPR_MAP[expr_key]["kr"]
        updated += 1

data["saved_expressions"] = exprs
with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"OK: {updated}/{len(exprs)} expressions upgraded with sentences+kr")
